[database]
host = "192.168.80.50"
port = 3306
user = "root"
password = "123456"
db = "devops_platform"
max_open = 5
max_idle = 2

[app]
addr = ":80"
env = "dev"

[log]
level = "debug"

[casbin]
model = "config/rbac_model.conf"
adapter = "file"
policy = "config/rbac_policy.csv"
auto_load = true
auto_load_interval = 30


