[gitlab]
address = "https://gitlab.corp.yatsenglobal.com"
private_token = "HmBPDkAC-NWx5Ro4GWUs"
hook_url = "https://testing-api-devops.corp.yatsenglobal.com"
hook_secret = "abc"
[tapd]
companyId = "40296318"
account = "ou#wok4Q"
token = "85DC09B1-BD25-33EB-3E89-259DF8F508D7"

[database]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
db = "skynetcl"
max_open = 5
max_idle = 2


[app]
addr = ":80"
env = "dev"

[sso]
client_id="rancher"
client_secret="771e6d6a-e041-4050-a91f-c662ed31bd5c"
auth_url="https://sso.cognixus.com/auth"
realm="Cognixus"

[log]
level = "debug"

[k8s]
expiration_option = [2,4,8,12,24]
