basePath: /
definitions:
  controller.FindByNameAndMobileResponse:
    properties:
      records:
        description: 记录
        items:
          $ref: '#/definitions/domain.User'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  domain.ChangePasswordCommand:
    properties:
      password:
        type: string
    type: object
  domain.CreateUserCommand:
    properties:
      email:
        type: string
      mobile:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/enum.SysRole'
      username:
        type: string
    type: object
  domain.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  domain.ModifyUserRoleCommand:
    properties:
      role:
        $ref: '#/definitions/enum.SysRole'
    type: object
  domain.ModifyUserStatusCommand:
    properties:
      status:
        type: integer
    type: object
  domain.User:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      enable:
        description: 1：启用   2：禁用
        type: integer
      id:
        type: string
      last_modified_at:
        type: string
      last_modified_by:
        type: string
      mobile:
        type: string
      name:
        type: string
      role:
        allOf:
        - $ref: '#/definitions/enum.SysRole'
        description: 0:普通用户，1:管理员，2:虚拟用户
      username:
        type: string
    type: object
  enum.SysRole:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - SysRoleGeneralUser
    - SysRoleAdminUser
    - SysRoleVirtualUser
host: 127.0.0.1
info:
  contact:
    email: xin.zhang@hicom.com
    name: zhangxin
  description: 运维系统 api.
  title: 运维系统
  version: "2.0"
paths:
  /sso/login:
    get:
      consumes:
      - application/json
      description: 用户登录接口,用于通过用户名密码登录系统
      parameters:
      - description: 登录参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
      summary: 用户密码登录
      tags:
      - login
  /user:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户名称
        in: query
        name: name
        type: string
      - description: 每页数据条数
        in: query
        name: page_size
        type: string
      - description: 第几页
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FindByNameAndMobileResponse'
      summary: 根据名称查询用户信息
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建用户
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUserCommand'
      produces:
      - application/json
      responses:
        "201":
          description: '{"id":"1", "msg": "create success"}'
          schema:
            type: string
      summary: 创建用户
      tags:
      - user
  /user/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
      summary: 获取用户信息
      tags:
      - user
  /user/{id}/password:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新用户密码信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/domain.ChangePasswordCommand'
      produces:
      - application/json
      responses:
        "200":
          description: '{"msg": "modify success"}'
          schema:
            type: object
      summary: 更新用户密码
      tags:
      - user
  /user/{id}/role:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新用户角色信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/domain.ModifyUserRoleCommand'
      produces:
      - application/json
      responses:
        "200":
          description: '{"msg": "modify success"}'
          schema:
            type: object
      summary: 更新用户角色信息
      tags:
      - user
  /user/{id}/status:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新用户状态  1:启用  2：禁用
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/domain.ModifyUserStatusCommand'
      produces:
      - application/json
      responses:
        "200":
          description: '{"msg": "modify success"}'
          schema:
            type: object
      security:
      - ApiKeyAuth: []
      summary: 更新用户状态
      tags:
      - user
schemes:
- http
- https
swagger: "2.0"
